// Use https://finicky-kickstart.now.sh to generate basic configuration
// Learn more about configuration options: https://github.com/johnste/finicky/wiki/Configuration

// Generated by Finicky Kickstart 
// Save as ~/.finicky.js

module.exports = {
    defaultBrowser: "Browserosaurus",
    handlers: [
        {
	    match: "http://localhost:13337",
            browser: "Google Chrome"
        }
    ]
}
